# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='name',
            new_name='title',
        ),
    ]
