# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0002_auto_20160110_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='episode_qty',
            field=models.IntegerField(default=0, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u044d\u043f\u0438\u0437\u043e\u0434\u043e\u0432'),
        ),
        migrations.AddField(
            model_name='series',
            name='season_qty',
            field=models.IntegerField(default=0, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u0441\u0435\u0437\u043e\u043d\u043e\u0432'),
        ),
    ]
