# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0003_auto_20160110_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='year',
            field=models.IntegerField(blank=True, default=0, verbose_name='\u0433\u043e\u0434 \u0432\u044b\u043f\u0443\u0441\u043a\u0430'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.CharField(max_length=512, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
    ]
