# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0004_auto_20160111_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='year',
            field=models.IntegerField(default=0, verbose_name='\u0433\u043e\u0434 \u0432\u044b\u043f\u0443\u0441\u043a\u0430'),
        ),
    ]
