# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0006_auto_20160113_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
