# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0012_auto_20160114_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(default='slug', unique=True),
        ),
    ]
