# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0015_auto_20160114_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='slug',
        ),
    ]
