# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0016_remove_series_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0435\u0437\u043e\u043d\u0430')),
                ('season_num', models.IntegerField(verbose_name='\u043d\u043e\u043c\u0435\u0440 \u0441\u0435\u0437\u043e\u043d\u0430')),
            ],
            options={
                'verbose_name': '\u0421\u0435\u0437\u043e\u043d',
                'verbose_name_plural': '\u0421\u0435\u0437\u043e\u043d\u044b',
            },
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season_num',
        ),
        migrations.AlterField(
            model_name='episode',
            name='description',
            field=models.CharField(default='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u0435 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u043e', max_length=1024, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=128, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u044d\u043f\u0438\u0437\u043e\u0434\u0430'),
        ),
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.CharField(default='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u0435 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u043e', max_length=1024, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0441\u0435\u0440\u0438\u0430\u043b\u0430'),
        ),
        migrations.AddField(
            model_name='season',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vicat.Series'),
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vicat.Season'),
            preserve_default=False,
        ),
    ]
