# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 03:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0018_season_episodes_qty'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season_num',
            field=models.IntegerField(default=0, verbose_name='\u043d\u043e\u043c\u0435\u0440 \u0441\u0435\u0437\u043e\u043d\u0430'),
        ),
    ]
