# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0020_auto_20160116_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='episodes_qty',
            new_name='episode_qty',
        ),
    ]
