# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 08:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0021_auto_20160116_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='ep_in_season_qty',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='ep_in_series_qty',
        ),
    ]
