# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 07:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0022_auto_20160116_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='actors',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u0430\u043a\u0442\u0435\u0440\u044b'),
        ),
        migrations.AddField(
            model_name='series',
            name='director',
            field=models.CharField(blank=True, max_length=64, verbose_name='\u0440\u0435\u0436\u0438\u0441\u0435\u0440'),
        ),
        migrations.AddField(
            model_name='series',
            name='genre',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u0436\u0430\u043d\u0440'),
        ),
        migrations.AddField(
            model_name='series',
            name='title_trans',
            field=models.CharField(blank=True, max_length=256, verbose_name='\u043f\u0435\u0440\u0435\u0432\u043e\u0434 \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f'),
        ),
    ]
