# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 08:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vicat', '0023_auto_20160117_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False, verbose_name='\u0430\u043a\u0442\u0438\u0432')),
                ('torrent', models.CharField(blank=True, max_length=512, verbose_name='\u0442\u043e\u0440\u0440\u0435\u043d\u0442')),
                ('viewed', models.BooleanField(default=False, verbose_name='\u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0435\u043d')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vicat.Series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
