# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0024_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': '\u0421\u0442\u0430\u0442\u0443\u0441', 'verbose_name_plural': '\u0421\u0442\u0430\u0442\u0443\u0441\u044b'},
        ),
        migrations.AddField(
            model_name='status',
            name='tosearch',
            field=models.BooleanField(default=False, verbose_name='\u0438\u0441\u043a\u0430\u0442\u044c'),
        ),
    ]
