# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0027_series_show_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='dub_lang',
        ),
    ]
