# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0028_remove_series_dub_lang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='episode_qty',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u044d\u043f\u0438\u0437\u043e\u0434\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='series',
            name='episode_qty',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u044d\u043f\u0438\u0437\u043e\u0434\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='series',
            name='season_qty',
            field=models.IntegerField(default=0, editable=False, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u0441\u0435\u0437\u043e\u043d\u043e\u0432'),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=128, unique=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435'),
        ),
    ]
