# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0031_auto_20160126_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='note',
            field=models.CharField(blank=True, default='\u0437\u0430\u043c\u0435\u0442\u043a\u0438 \u0430\u0434\u043c\u0438\u043d\u0438\u0441\u0442\u0440\u0430\u0442\u043e\u0440\u0430', max_length=1024, verbose_name='\u0437\u0430\u043c\u0435\u0442\u043a\u0438'),
        ),
    ]
