# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0032_auto_20160126_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='description',
            field=models.CharField(blank=True, default='\u041e\u043f\u0438\u0441\u0430\u043d\u0438\u0435 \u043d\u0435 \u043e\u0444\u043e\u0440\u043c\u043b\u0435\u043d\u043e', max_length=1024, verbose_name='\u043e\u043f\u0438\u0441\u0430\u043d\u0438\u0435'),
        ),
        migrations.AlterField(
            model_name='series',
            name='preview',
            field=models.CharField(blank=True, default='dummy_series.jpg', max_length=128, verbose_name='\u0444\u043e\u0442\u043e'),
        ),
    ]
