# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0035_auto_20160130_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': '\u041e\u0431\u0437\u043e\u0440', 'verbose_name_plural': '\u041e\u0431\u0437\u043e\u0440\u044b'},
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
