# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0037_remove_review_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=128, verbose_name='\u0437\u0430\u0433\u043e\u043b\u043e\u0432\u043e\u043a'),
        ),
    ]
