# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 03:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0042_auto_20160131_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=256, verbose_name='\u0442\u0435\u043a\u0441\u0442'),
        ),
    ]
