# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 03:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0044_auto_20160201_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0, verbose_name='\u043a\u043e\u043b-\u0432\u043e \u043b\u0430\u0439\u043a\u043e\u0432'),
        ),
    ]
