# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0046_auto_20160204_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='preview',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='\u0444\u043e\u0442\u043e'),
        ),
    ]
