# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0048_auto_20160204_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='preview',
            new_name='im_sourse',
        ),
    ]
