# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0052_auto_20160205_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='preview',
            field=models.CharField(blank=True, default='dummy_series.jpg', max_length=128, null=True, verbose_name='\u043d\u0430\u0437\u0432\u0430\u043d\u0438\u0435 \u0444\u043e\u0442\u043e'),
        ),
    ]
