# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0054_auto_20160205_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='im_sourse',
            field=models.ImageField(blank=True, default='images/None/no_img_series.jpg', upload_to='images/', verbose_name='\u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0444\u043e\u0442\u043e'),
        ),
    ]
