# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0055_series_im_sourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='im_sourse',
        ),
    ]
