# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0059_auto_20160207_1851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='preview',
        ),
    ]
