# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0060_remove_episode_preview'),
    ]

    operations = [
        migrations.RenameField(
            model_name='series',
            old_name='preview',
            new_name='preview_series',
        ),
    ]
