# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0063_remove_series_image_series'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image_series',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='\u0438\u0441\u0442\u043e\u0447\u043d\u0438\u043a \u0444\u043e\u0442\u043e'),
        ),
    ]
