# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0065_auto_20160212_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='slug',
            field=models.SlugField(blank=True, max_length=30),
        ),
    ]
