# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0066_auto_20160212_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='image_episode',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='\u0434\u0430\u043d\u043d\u044b\u0435 \u043e \u0444\u043e\u0442\u043e_\u044d\u043f'),
        ),
        migrations.AlterField(
            model_name='series',
            name='image_series',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='\u0434\u0430\u043d\u043d\u044b\u0435 \u043e \u0444\u043e\u0442\u043e_\u0441\u0435\u0440'),
        ),
    ]
