# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-14 07:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vicat', '0070_auto_20160213_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series',
            name='preview_episode',
        ),
        migrations.RemoveField(
            model_name='series',
            name='preview_series',
        ),
    ]
